### ISSUE TITLE
Client server GUI

### ISSUE THREAD

**Issue by headhunter94** [jacklam718/ftp#1]
I executed the FTP server and client to see it how it works out of curiosity. Cleared all the dependecies. But when both are run using the python command nothing is shown in the GUI. please help.
Thank you

**Comment by jacklam718** [comment]
@headhunter94 
1. Did you install PyQt4? If so, what version of it?
2. What version of Python are you using?
3. Any errors? if any, can you post error messages here?
4. What OS are you using?
Thanks.

**Comment by headhunter94** [comment]
Thank you for replying.
 Yes installed PyQt4 today.
I have python 2.7
I am not getting any errors. only negligible warnings.
I am using Deepin 15 OS.
Thanks

**Comment by jacklam718** [comment]
I only tried on MacOS...

**Comment by headhunter94** [comment]
I will try on windows and report again

**Comment by jacklam718** [comment]
Did you connect to ftp server by clicking this button?
<img width="61" alt="screen shot 2017-11-24 at 12 20 04 pm" src="https://user-images.githubusercontent.com/5494638/33195373-df4d2118-d111-11e7-930d-91f92eedef5b.png">

**Comment by headhunter94** [comment]
after clicking that what host name should i enter

**Comment by jacklam718** [comment]
Enter the IP address of the FTP server. If you're running the FTP server on your local machine then you can enter `127.0.0.1`

**Comment by headhunter94** [comment]
Initially I entered the same but nothing happened

**Comment by headhunter94** [comment]
i executed the ftp_client and ftp_server 
the window pops up and after entering the address nothing is happening

**Comment by jacklam718** [comment]
any errors?

**Comment by headhunter94** [comment]
Nope

**Comment by headhunter94** [comment]
Should i execute any other files like the utils or setup?

**Comment by jacklam718** [comment]
no

**Comment by headhunter94** [comment]
AttributeError: 'QByteArray' object has no attribute 'find'

**Comment by headhunter94** [comment]
i got the error while doing python client code

**Comment by headhunter94** [comment]
Please do help. Your code will save my life.!
Thank you

**Comment by jacklam718** [comment]
I have no idea yet. sorry

**Comment by headhunter94** [comment]
i downloaded the zip. unzipped on desktop. First i run the server and then run the client and enter 127.0.0.1 and nothing happens. Am i doing something wrong?

**Comment by jacklam718** [comment]
@headhunter94 I've Fixed. You can try again.

**Comment by headhunter94** [comment]
Thank you for the effort.
I tried the same. nothing is happening. the client window GUI is opening but after entering 127.0.0.1 nothing seems to happen.
on the client Terminal i get this:
**Traceback (most recent call last):
  File "ftp_client.py", line 176, in connect
    raise error
**
on the server terminal:
**2017-11-25 15-01-41 [-] Start ftp server: Enter q or Q to stop ftpServer...
2017-11-25 15-01-41 [-] Server started: Listen on: 127.0.1.1, 21**

what should i do?

**Comment by jacklam718** [comment]
@headhunter94 Really sorry about that!! This time should be ok. You can git pull and try again. I screwed up something by my recent code refactoring.
So, if you have any problems you can `git checkout` to this branch `17360298a8bb5149562a14ae176a901e23f057db` it should works perfectly.
